sudo: required
language: python

jobs:
  include:
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: bionic
      python: 3.6

addons:
  apt:
    packages:
      - texlive-full
      - pandoc
      - pandoc-citeproc

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - make